### ISSUE TITLE
[FR] Missing parameters

### ISSUE THREAD

**Issue by Sineos** [JoJ123/ioBroker.mihome-airpurifier#10]
Firstly, many thanks for this adapter. Really appreciated.
miio is supporting a few more properties and actions. It would be great to extend the adapter to them as well:

```
Properties:
  - power: true
  - mode: favorite
  - temperature: 22.3
  - humidity: 40
  - aqi: 325
  - favoriteLevel: 5
  - filterLifeRemaining: 98
  - filterHoursUsed: 46
  - led: true
  - ledBrightness: unknown
  - buzzer: false

Actions:
  Mode - cap:mode
    modes

  Sensor - type:sensor
    values

  LED - cap:miio:led-brightness, cap:miio:switchable-led
    ledBrightness [string]
    led [boolean]

  miIO - type:miio
    miioModel
    miioProperties
    miioCall string [array]

  Other actions
    buzzer [boolean]
    setBuzzer boolean
    getBuzzer
    pm2_5
    pm2.5
    relativeHumidity
    rh
    temperature
    mode [string]
    setMode [string]
    power [boolean]
    setPower boolean
    togglePower
    turnOn
    turnOff
    restorableState
    captureState
    setState object
    state
```

**Comment by JoJ123** [comment]
Are you interessted in all of these states? 
Or do you have special wishes?

**Comment by GhostCHS** [comment]
Because im interested. Is it possible to reset the remaining filter life if the parameter is involved?

**Comment by MickL** [comment]
Im very much interested / i find mostly useful:

- Setting led (on/off) -> Very important for night
- Reading filterLifeRemaining & filterHoursUsed

Nice to have:

- Setting ledBrightness
- Setting buzzer (Soundeffect when changing some value. In the Mi app even the volume can be changed)

**Comment by JoJ123** [comment]
@MickL @GhostCHS @Sineos I've added in version 0.1.5:
- filterLifeRemaining 
- filterHoursUsed
- led 
- buzzer

Can you please test it.

@Sineos I had to go back to the default miio version. In your fork it was not possible to read the buzzer

**Comment by MickL** [comment]
Thanks for you efforts. I already switched to Home Aasistant a long time ago so I cant test, sorry.

**Comment by JoJ123** [comment]
@MickL Thx for the feedback, how is your experience with HA compared to ioBroker? :)

**Comment by MickL** [comment]
I cant compare but the experience is very nice. Everything just works and is implemented or has addons. What I dont like is that the base code is not modular, e.g. the miio package is part of a single repository that contains like 100 packages. But so far everything worked out pretty well.
