### ISSUE TITLE
0.0.5: After clean installation of ioBroker, adapter is not starting

### ISSUE THREAD

**Issue by FRYYYYYY** [JoJ123/ioBroker.mihome-airpurifier#18]
After a full clean install of ioBroker with its new routine, the airpurifier adapter is not starting. Installation and configuration is working, but it won't start:

![image](https://user-images.githubusercontent.com/13643787/54239126-956e2280-451a-11e9-8d60-d207d7b2ca32.png)

**Comment by xxPunikaxx** [comment]
same issue after installing new ioBroker with debian stretch image. Please provide a solution.


Caught | 2019-03-16 16:23:32.797 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29 code: 'MODULE_NOT_FOUND' }
-- | -- | -- | --
Caught | 2019-03-16 16:23:32.796 | error | by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
Caught | 2019-03-16 16:23:32.796 | error | by controller[0]: at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-airpurifier/main.js:98:14)
Caught | 2019-03-16 16:23:32.796 | error | by controller[0]: at new miairpurifier (/opt/iobroker/node_modules/iobroker.mihome-airpurifier/miairpurifier.js:38:20)
mihome-airpurifier.0 | 2019-03-16 16:23:32.739 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
mihome-airpurifier.0 | 2019-03-16 16:23:32.739 | error | at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
mihome-airpurifier.0 | 2019-03-16 16:23:32.739 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-airpurifier/main.js:98:14)
mihome-airpurifier.0 | 2019-03-16 16:23:32.739 | error | at new miairpurifier (/opt/iobroker/node_modules/iobroker.mihome-airpurifier/miairpurifier.js:38:20)

**Comment by FRYYYYYY** [comment]
The forked version of Apollon77 does not have those problems:
https://github.com/Apollon77/ioBroker.mihome-airpurifier

**Comment by JoJ123** [comment]
I don't see any changes that could break the adapter between the fork and my master branch. Can you please try it again with the newest master branch?

**Comment by JoJ123** [comment]
@FRYYYYYY Can you please try again with the newest master branch?

**Comment by FRYYYYYY** [comment]
@JoJ123 It's working with your latest branch. Thanks a lot!

**Comment by JoJ123** [comment]
@FRYYYYYY Thx for the answer, I will create a new version for npm tomorrow.
