### ISSUE TITLE
Add Support for "Smartmi Evaporative Humidifier"

### ISSUE THREAD

**Issue by Ilovegym66** [JoJ123/ioBroker.mihome-airpurifier#23]
see here:
https://github.com/ioBroker/ioBroker.mihome/issues/83

**Comment by JoJ123** [comment]
@Ilovegym66 We could create a new adapter for that, are you open to assist? 
I don't have that device so you have to support me with testing.

**Comment by IckZ** [comment]
I would like to help you. Ive got the device. What do you need? tmp the log says that the Handshake is not possible: can not be connected.Error: Could not connect to device, handshake timeout.

**Comment by IckZ** [comment]
Sry.. it already seems to work with the Adapter. Ive just made a type error in the token. Now the values appear. Great work!
