### ISSUE TITLE
No Connection to the Purifiers

### ISSUE THREAD

**Issue by Wiggins2610** [JoJ123/ioBroker.mihome-airpurifier#24]
Hi,
got no connection and the following LOG. 
Did work already with two Airs, but after Updating to new iobroker version I get no connection. Any ideas or fix? Thank you in advance! 

Caught | 2019-06-24 19:36:33.494 | error | by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:54) code: 'MODULE_NOT_FOUND' }
-- | -- | -- | --
Caught | 2019-06-24 19:36:33.494 | error | by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5289:18)
Caught | 2019-06-24 19:36:33.494 | error | by controller[0]: at Adapter.emit (events.js:208:7)
Caught | 2019-06-24 19:36:33.494 | error | by controller[0]: at emitNone (events.js:106:13)
Caught | 2019-06-24 19:36:33.493 | error | by controller[0]: at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-airpurifier/main.js:98:14)
Caught | 2019-06-24 19:36:33.493 | error | by controller[0]: at new miairpurifier (/opt/iobroker/node_modules/iobroker.mihome-airpurifier/miairpurifier.js:38:20)
Caught | 2019-06-24 19:36:33.493 | error | by controller[0]: at require (internal/module.js:11:18)
Caught | 2019-06-24 19:36:33.493 | error | by controller[0]: at Module.require (module.js:597:17)
Caught | 2019-06-24 19:36:33.493 | error | by controller[0]: at Function.Module._load (module.js:475:25)
Caught | 2019-06-24 19:36:33.493 | error | by controller[0]: at Function.Module._resolveFilename (module.js:548:15)
Caught | 2019-06-24 19:36:33.492 | error | by controller[0]: { Error: Cannot find module 'es6-promise'

**Comment by Wiggins2610** [comment]
No news or any comment on this?

**Comment by Ahrenfelde** [comment]
Any updates? Are you able to connect your purifier?

**Comment by Wiggins2610** [comment]
Seit ein paar Wochen geht es wieder. 
Hatte den iobroker als solchen upgedatet, seitdem läuft es wieder. 
Node.js: v10.17.0
NPM: 6.11.3
