### ISSUE TITLE
Can´t get token of purifier 2S

### ISSUE THREAD

**Issue by Ahrenfelde** [JoJ123/ioBroker.mihome-airpurifier#30]
Hi,

i am unable to get the token. I install the miio command line tool and try to get the informations with miio discover. But i only get ??? as token. 

The air filter is connected to home WiFi with the mi home app for ios.

I run the tool under Ubuntu as "direct" system, (no VM).

Can anyone help me to get the token?
Sadly i got no android device here, only a Windows PC and iphone/ipad and a linux machine as iobroker/smarthome server.

**Comment by totti1171** [comment]
Hi, inzwischen erfolgreich?

**Comment by Ahrenfelde** [comment]
Yes
