### ISSUE TITLE
mi air purifier 3

### ISSUE THREAD

**Issue by jenskaschub** [JoJ123/ioBroker.mihome-airpurifier#31]
Hi, 
I've the new version (zhimi.airpurifier.mb3). Could you add this one?

**Comment by Sineos** [comment]
miio library is updated to include zhimi.airpurifier.mb3
Work is attributed to @mouth4war and @kingkong123

Seemed to be a major update since the new models changed their data structure. Don't know if it will work out of the box in the adapter.

**Comment by jenskaschub** [comment]
I think it's now implemented in the python-miio https://github.com/rytilahti/python-miio/pull/585?fbclid=IwAR1azkC1nkfjVWmCu5-9n_3ZO89roEn-GNEnZLdFp9Yran9a_QzBfCIJUr8 perhaps that helps

**Comment by JoJ123** [comment]
@Sineos Tested the new version from @kingkong123, but it seems that there is more work to do.

**Comment by totti1171** [comment]
what's new?

have just tested the latest version - error message: "Wrong device"

**Comment by Goeks1** [comment]
I have the 3H version and want to include it to my IoBroker, but first tutorial in the readme does work.
The tool miio discover show only three questionmarks instead of the token.

Output of miio:

```
INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 270xxxxxx
Model info: Unknown
Address: 192.168.1.204
Token: ???
Support: Unknown
```

**Comment by JoJ123** [comment]
@Goeks1 I can't help with the version 3. I don't have that device.
You can try to create a small local project with the miio version from @kingkong123

If you have something to share I will try to integrate it.
