### ISSUE TITLE
Adapter can not be installed - npm ERR! path gitnpm Err! ...

### ISSUE THREAD

**Issue by kuesimon** [JoJ123/ioBroker.mihome-airpurifier#37]
**Describe the bug**  
I wanted to install the adapter from the iobroker adapter list and get the following error message.

**To Reproduce**  
The error occured during normal installation via "+"-sign
![image](https://user-images.githubusercontent.com/20601866/80517118-d9bdbb80-8984-11ea-9642-c51750516b13.png)

**Screenshots & Logfiles**  
This is the error message:
![image](https://user-images.githubusercontent.com/20601866/80517166-f22dd600-8984-11ea-8f38-6c3ee9340bd9.png)

**Versions:**  
 - Adapter version: 0.1.1
 - JS-Controller version: <js-controller-version> iobroker -v : 3.0.19
 - Node version: <node-version> v10.15.3
 - Operating system: debian

**Comment by JoJ123** [comment]
@kuesimon Can you try with the new version 0.1.3 please.

**Comment by JoJ123** [comment]
@kuesimon 
Try to install it directly from the master branch:
https://github.com/JoJ123/ioBroker.mihome-airpurifier

**Comment by kuesimon** [comment]
I did the installation from github (via the selection in github installation and via direkt link)

![image](https://user-images.githubusercontent.com/20601866/80815827-9fdff580-8bce-11ea-83bd-d5fd904e8c6a.png)

![image](https://user-images.githubusercontent.com/20601866/80815938-d4ec4800-8bce-11ea-8b7d-eff64a7c09a6.png)

In both cases it's the same error.

**Comment by JoJ123** [comment]
@kuesimon Please try again from Master

**Comment by kuesimon** [comment]
now the installation is working!!

**Comment by JoJ123** [comment]
Perfect :)

kuesimon <notifications@github.com> schrieb am Fr., 1. Mai 2020, 17:50:

**Comment by JoJ123** [comment]
@kuesimon Please try again with the latest version 0.1.6.
I had to revert back to the github fork.

**Comment by FRYYYYYY** [comment]
Ich habe einen ähnlichen Fehler... update funktionierte nicht, dann Adapter deinstalliert, lässt sich aber nicht mehr installieren. Dabei ist es egal ob aus dem normalen Repo oder direkt von GitHub:

![image](https://user-images.githubusercontent.com/13643787/80860923-68735680-8c6b-11ea-9437-bfff64426f33.png)

Andere Adapter lassen sich installieren. Daher würde ich den eigentlichen Fehler ausschließen, dass GitHub nicht erreichbar wäre...

Per wget vom RPi kann auch alles heruntergeladen werden:

![image](https://user-images.githubusercontent.com/13643787/80860952-9fe20300-8c6b-11ea-8d12-0f1a2ce3c9e7.png)

**Comment by JoJ123** [comment]
The problem is, that your raspberry can't resolve the miio package that is
linked to my fork.

I will check for a solution.

FRYYYYYY <notifications@github.com> schrieb am Sa., 2. Mai 2020, 11:54:

**Comment by JoJ123** [comment]
@FRYYYYYY @kuesimon I've pushed a new version 0.1.8. Please try it directly from Github.

**Comment by JoJ123** [comment]
@FRYYYYYY You managed to install the latest version?

**Comment by FRYYYYYY** [comment]
I installed the latest version from github and it’s working, yes.

**Comment by JoJ123** [comment]
Okay perfect. I've released the version on npm, so it will be available soon directly inside ioBroker.
